service:
    SERVER_HOST : 'localhost'
    SERVER_PORT : 5050

click_log_processor:
    NUM_OF_CLASSES : 17
    INITIAL_P : 0.058823529 # 1/NUM_OF_CLASSES
    ALPHA : 0.1
    SLEEP_TIME_IN_SECONDS : 1
    LOG_CLICKS_TASK_QUEUE_URL : 'amqp://tkaptoww:acPAHfHFf-uIpoR7vlR_uh4ehMlCAuv7@otter.rmq.cloudamqp.com/tkaptoww'
    LOG_CLICKS_TASK_QUEUE_NAME : "tap-news-log-clicks-task-queue"
    PREFERENCE_MODEL_TABLE_NAME : 'user_preference_model'
    NEWS_TABLE_NAME : 'news'
